services:
  chtt_db:
    image: mysql:latest
    container_name: chtt_db
    environment:
      MYSQL_ROOT_PASSWORD: chtt_hd
      MYSQL_DATABASE: chtt_db
      MYSQL_USER: chtt_user
      MYSQL_PASSWORD: chtt_user_pass
    ports:
      - "6033:3306"
    volumes:
      - chtt_dbdata:/var/lib/mysql
  chtt_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chtt_pma
    links:
      - chtt_db
    environment:
      PMA_HOST: chtt_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  chtt_dbdata:
